### PR TITLE
Fixed issue where report query by tag_ids would not work.

### PR DESCRIPTION
**Pull request by tylerrbrown**

### CODE REVIEW

**Comment by chrisofspades** [comment]
@sochix Please review/approve this pull request. It fixes not only tag_ids but all List<int> properties. Thank you.

**Comment by timgaunt** [comment]
This is also causing us issues, can this be pulled in please

**Comment by sochix** [comment]
Merged! Thanks @tylerrbrown for your PR

**Comment by timgaunt** [comment]
@sochix any idea when it will be released on nuget?

**Comment by sochix** [comment]
I will do it ASAP

**Pull request merged**
