### PR TITLE
Async methods

### PR DESCRIPTION
**Pull request by LazyTarget**
Support for Async methods
Seperated into two projects; .NET 4.0 and .NET 4.5

### CODE REVIEW

**Comment by LazyTarget** [comment]
When creating the NuGet package, make it so that both .NET frameworks are available

**Comment by sochix** [comment]
Why we need two versions for .net 40 and .net 4.5? Because of await/async?

**Comment by LazyTarget** [comment]
Yes, async and await was introduced with .NET 4.5.
And it is the preferred way of doing asynchronous methods

**Comment by sochix** [comment]
What you think about using (restsharp library)[http://restsharp.org/] for TogglAPI library?

**Comment by LazyTarget** [comment]
I think that would be good leave the rest requests to a well known library. Leaving the ToggleAPI to only keep track of Toggle things.

**Pull request merged**
